apiVersion: v1
kind: Service
metadata:
  name: eks-hello-linux-service
  namespace: eks-hello-app
  labels:
    app: eks-hello-linux-app
spec:
  type: LoadBalancer
  selector:
    app: eks-hello-linux-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080