apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-hello-linux-deployment
  namespace: eks-hello-app
  labels:
    app: eks-hello-linux-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eks-hello-linux-app
  template:
    metadata:
      labels:
        app: eks-hello-linux-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - arm64
      containers:
        - name: hello-container
          image: 588184019567.dkr.ecr.ap-southeast-1.amazonaws.com/hello/helloservice:7c331f7286a832c5680fab99f813b0f720bd0fd8
          ports:
            - name: http
              containerPort: 80
          imagePullPolicy: IfNotPresent
      nodeSelector:
        kubernetes.io/os: linux